from typing import Any, Optional, Tuple, Union, BinaryIO, Iterator, Type, TypeVar, Any


class Sequence:
    name: str
    sequence: str
    qualities: Optional[str]
    def __init__(self, name: str, sequence: str, qualities: Optional[str] = ...) -> None: ...
    def __getitem__(self, s: slice) -> Sequence: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __richcmp__(self, other: Sequence, op: int) -> bool: ...
    def qualities_as_bytes(self) -> bytes: ...
    def fastq_bytes(self) -> bytes: ...
    def fastq_bytes_two_headers(self) -> bytes: ...

class BytesSequence:
    name: bytes
    sequence: bytes
    qualities: bytes

    def __init__(self, name: bytes, sequence: bytes, qualities: bytes = ...) -> None: ...
    def __getitem__(self, s: slice) -> BytesSequence: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __richcmp__(self, other: BytesSequence, op: int) -> bool: ...
    def fastq_bytes(self) -> bytes: ...
    def fastq_bytes_two_headers(self) -> bytes: ...

def paired_fastq_heads(buf1: Union[bytes,bytearray], buf2: Union[bytes,bytearray], end1: int, end2: int) -> Tuple[int, int]: ...
def record_names_match(header1: str, header2: str) -> bool: ...
def record_names_match_bytes(header1: bytes, header2: bytes) -> bool: ...

T = TypeVar("T")
class fastq_iter:
    def __init__(self, file: BinaryIO, sequence_class: Type[T], buffer_size: int = ...): ...
    def __iter__(self) -> Iterator[T]: ...
    def __next__(self) -> T: ...

    @property
    def n_records(self) -> int: ...
