class SequenceRecord:
    name: bytes
    sequence: bytes
    qualities: bytes
    def __init__(self, name: bytes, sequence: bytes, qualities: bytes = ...) -> None: ...
    def __repr__(self) -> str: ...
    def fastq_bytes(self) -> bytes: ...
    def fastq_bytes_two_headers(self) -> bytes: ...


